name: Update Plugins-dev

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_S3_BUCKET: falco-distribution
  AWS_S3_PREFIX: plugins
  AWS_S3_REGION: eu-west-1

jobs:
  release-plugins-dev-x86:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Plugins ‚§µÔ∏è
        uses: actions/checkout@v3

      - name: Run x86 build üèóÔ∏è
        run: make packages

      - name: Configure AWS credentials üîß‚öôÔ∏è
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "arn:aws:iam::292999226676:role/github_actions-plugins-s3"
          aws-region: ${{ env.AWS_S3_REGION }}

      - name: Upload files to S3 ‚¨ÜÔ∏è
        if: github.event_name == 'push'
        run: |
          for package in output/*.tar.gz; do
            aws s3 cp --no-progress $package s3://${{ env.AWS_S3_BUCKET}}/${{ env.AWS_S3_PREFIX }}/dev/
          done

  release-plugins-dev-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Plugins ‚§µÔ∏è
        uses: actions/checkout@v3
      
      - name: Run arm64 build üèóÔ∏è
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu_latest
          githubToken: ${{ github.token }}

          setup: |
            mkdir -p "${PWD}/artifacts"

          dockerRunArgs:
            --volume "${PWD}/artifacts:/artifacts"
 
          install: |
            apt-get update && apt-get install -y --no-install-recommends build-essential git ca-certificates golang curl && apt-get clean
            update-ca-certificates
            git config --global --add safe.directory ${{ github.workspace }}
            
          run: |
            make packages
            cp -R output/* /artifacts

      - name: Configure AWS credentials üîß‚öôÔ∏è
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "arn:aws:iam::292999226676:role/github_actions-plugins-s3"
          aws-region: ${{ env.AWS_S3_REGION }}

      - name: Upload files to S3 ‚¨ÜÔ∏è
        if: github.event_name == 'push'
        run: |
          for package in artifacts/*.tar.gz; do
            aws s3 cp --no-progress $package s3://${{ env.AWS_S3_BUCKET}}/${{ env.AWS_S3_PREFIX }}/dev/
          done